# SPDX-FileCopyrightText: 2024 Margo
#
# SPDX-License-Identifier: MIT
#
# Author: Christian Storm <christian.storm@siemens.com>
---
name: GitHub Pages

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      # create local virtualenv to enable caching in CI
      - name: Configure poetry
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ./.venv
          # cache is invalidated if dependencies change
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install the project dependencies
        run: poetry install

      - name: Build Pages
        run: poetry run -- mkdocs build

      - name: GitHub Pages Deploy
        # only deploy if we are on the default branch
        if: ${{ github.ref == 'refs/heads/pre-draft' }}
        run: poetry run -- mkdocs gh-deploy --force --clean --verbose
